Repository lamnguyencse17/smart-lighting, pull requests merged in 2020-06, with the labels that each got.

#25 Implemented #21 Requirements
  public/index.css
  src/client/Dashboard/DeviceView/DeviceModal.js
  src/client/Dashboard/DeviceView/DevicePanel.js
  src/server/models/schedules.js
  src/server/routes/models/schedules.js
Labels: adapt, enhancement

#31 Implement #19 Requirements
  public/index.css
  src/client/Dashboard/DeviceView/ModalComponents/Schedule.js
  src/client/Dashboard/SensorView/ModalComponent/AreaSelector.js
  src/client/Dashboard/SensorView/ModalComponent/ConditionSelecter.js
  src/client/Dashboard/SensorView/ModalComponent/DeviceSelector.js
  src/client/Dashboard/SensorView/SensorModal.js
  src/client/Dashboard/SensorView/SensorPanel.js
Labels: enhancement

#51 Issue #40
  src/client/Dashboard/SensorView/ModalComponent/ConditionSelecter.js
  src/client/Dashboard/SensorView/ModalComponent/SensorSelector.js
  src/client/Dashboard/SensorView/SensorModal.js
  src/client/Dashboard/SensorView/SensorPanel.js
Labels: enhancement

#63 Implementing Issue #49
  public/index.css
  src/client/Dashboard/SensorView/ModalComponent/AreaSelector.js
  src/client/Dashboard/SensorView/ModalComponent/ConditionSelecter.js
  src/client/Dashboard/SensorView/ModalComponent/DeviceSelector.js
  src/client/Dashboard/SensorView/ModalComponent/SensorSelector.js
  src/client/Dashboard/SensorView/SensorModal.js
  src/server/helpers/messageHandler.js
  src/server/routes/models/conditions.js
  src/server/server.js
Labels: adapt, enhancement

#65 Setup and Initial Test For Issue #53
  .gitignore
  package-lock.json
  package.json
  src/client/Dashboard/DeviceView.js
  src/client/Dashboard/__tests__/AreaView.js
  src/client/Dashboard/__tests__/Dashboard.js
  src/client/Dashboard/__tests__/DeviceView.js
  src/client/Dashboard/__tests__/SensorView.js
  src/client/__tests__/AlertModal.js
  src/client/__tests__/App.js
  src/client/actions/__tests__/alert.js
  src/client/actions/alert.js
  src/client/reducers/__tests__/alert.js
  src/client/reducers/alert.js
  src/setupTests.js
  src/test-utils.js
Labels: dependencies, enhancement

#68 Limit numbers of readings and history getting from database #55
  src/server/routes/models/areas.js
  src/server/routes/models/devices.js
  src/server/routes/models/sensors.js
Labels: enhancement
