Repository lamnguyencse17/smart-lighting, pull requests merged in 2020-07, with the labels that each got.

#88 Add setAlert Actions To All Error Handler #74
  src/client/actions/device.js
  src/client/actions/sensor.js
  src/client/actions/user.js
Labels: enhancement

#90 Fix mongoose populate in #48 (untested)
  src/server/helpers/executeCondition.js
  src/server/models/sensors.js
  src/server/server.js
Labels: bug

#100 Hot Fix Bugs From Issues, Implementing #98
  package-lock.json
  package.json
  src/client/Dashboard/SensorView.js
  src/client/Dashboard/SensorView/ChartPanel.js
  src/client/Dashboard/SensorView/SensorModal.js
  src/client/Dashboard/SensorView/SensorPanel.js
  src/client/Dashboard/SensorView/__tests__/ConditionView.js
  src/server/models/sensors.js
  src/server/routes/models/sensors.js
Labels: bug, dependencies, enhancement

#105 implementing issue #106
  src/client/Dashboard/SensorView.js
  src/client/Dashboard/SensorView/ConditionDeleteButton.js
  src/client/Dashboard/SensorView/ConditionView.js
  src/client/Dashboard/SensorView/SensorPanel.js
  src/client/actions/sensor.js
  src/client/actions/types.js
  src/client/reducers/sensor.js
Labels: enhancement

#102 Create ChartPanel Component #77
  src/client/Dashboard/SensorView/ChartPanel.js
  src/client/Dashboard/SensorView/SensorPanel.js
  src/server/routes/models/sensors.js
Labels: enhancement

#112 Fix ChartPanel bugs after the merge to master #111
  src/client/Dashboard/SensorView/ChartPanel.js
Labels: bug
